{
  pkgs,
  inputs,
  lib,
  config,
  ...
}: let
  rill = let
    zig = pkgs.zig_0_16;
  in
    pkgs.stdenvNoCC.mkDerivation (finalAttrs: {
      name = "rill";
      src = pkgs.fetchFromCodeberg {
        repo = "rill";
        owner = "lzj15";
        rev = "79100bfef18e2347754856b112e9ea27da4a1bda";
        hash = "sha256-J6z+d8iRHXx9vDf3izQHcS/Tj2K2VKUVDQoxBY1E6MU=";
      };

      buildInputs = with pkgs; [
        wayland
        wayland-protocols
        wayland-scanner
        libxkbcommon
      ];
      nativeBuildInputs = [
        zig
        pkgs.pkg-config
      ];
      zigBuildFlags = [
        "--system"
        "${finalAttrs.deps}"
      ];

      strictDeps = true;
      # TODO this was annoying, just generate on flake updates
      deps = pkgs.callPackage (
        # generated by zon2nix (https://github.com/nix-community/zon2nix)
        {
          linkFarm,
          fetchzip,
          fetchgit,
        }:
          linkFarm "zig-packages" [
            {
              name = "N-V-__8AAA3xAgD5Kwpwii8EK-ddKekNkv4zv8rJiDhDHLuI";
              path = fetchzip {
                url = "https://codeberg.org/river/river/archive/v0.4.8:protocol.tar.gz";
                hash = "sha256-KsgaDFg3lQGt53sCKXumYmWWfuH3iritU211fnuZkJQ=";
              };
            }
            {
              name = "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX";
              path = fetchzip {
                url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.6.0.tar.gz";
                hash = "sha256-3m/ITNhZUJ/5uD/Tqm+0uZSktGoYgWF5oldOqOCUkIE=";
              };
            }
            {
              name = "xkbcommon-0.4.0-VDqIe0i2AgDRsok2GpMFYJ8SVhQS10_PI2M_CnHXsJJZ";
              path = fetchzip {
                url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.4.0.tar.gz";
                hash = "sha256-zQkmP/cuhAtjOLqYS5D15khKzpqyhbyZ0TD6/8jOkqE=";
              };
            }
          ]
      ) {};
    });
in {
  imports = [../wayland/home.nix];

  home.packages = [
    rill
  ];
  xdg.configFile = {
    "river/init" = {
      text = ''
        #!/bin/sh
        ${rill}/bin/rill
      '';
      executable = true;
    };
    "rill/config.zon" = let
      cfg = (import ./config.nix) {inherit pkgs config lib;};

      # handles strings that start with '.' as enum values
      # Any -> String
      nix2Zon = val:
        with builtins; let
          # TODO make invalid names valid with @"bad-name"
          # pub fn isValidId(bytes: []const u8) bool {
          #     if (bytes.len == 0) return false;
          #     for (bytes, 0..) |c, i| {
          #         switch (c) {
          #             '_', 'a'...'z', 'A'...'Z' => {},
          #             '0'...'9' => if (i == 0) return false,
          #             else => return false,
          #         }
          #     }
          #     return std.zig.Token.getKeyword(bytes) == null;
          # }
          #
          # String -> Bool
          isValidId = s:
            if any (v: s == v) ["addrspace" "align" "allowzero" "and" "anyframe" "anytype" "asm" "break" "callconv" "catch" "comptime" "const" "continue" "defer" "else" "enum" "errdefer" "error" "export" "extern" "fn" "for" "if" "inline" "noalias" "noinline" "nosuspend" "opaque" "or" "orelse" "packed" "pub" "resume" "return" "linksection" "struct" "suspend" "switch" "test" "threadlocal" "try" "union" "unreachable" "var" "volatile" "while"]
            then false
            else if any (v: (substring 0 1 s) == v) genList toString 10
            then false
            else if foldr
            then false
            else true;

          # /// Print the string as escaped contents of a double quoted string.
          # pub fn stringEscape(bytes: []const u8, w: *Writer) Writer.Error!void {
          #     for (bytes) |byte| switch (byte) {
          #         '\n' => try w.writeAll("\\n"),
          #         '\r' => try w.writeAll("\\r"),
          #         '\t' => try w.writeAll("\\t"),
          #         '\\' => try w.writeAll("\\\\"),
          #         '"' => try w.writeAll("\\\""),
          #         '\'' => try w.writeByte('\''),
          #         ' ', '!', '#'...'&', '('...'[', ']'...'~' => try w.writeByte(byte),
          #         else => {
          #             try w.writeAll("\\x");
          #             try w.printInt(byte, 16, .lower, .{ .width = 2, .fill = '0' });
          #         },
          #     };
          # }

          # from nixpkgs.lib
          # String -> [String]
          stringToCharacters = s: genList (p: substring p 1 s) (stringLength s);

          # String -> String
          # TODO finish: for rill this is not really needed, but for furture needs ?
          stringEscape = s: concatStringSep "" (map (x: x) (stringToCharacters s));

          printId = val: (
            if isValidId val
            then val
            else ("@\"" + (stringEscape val) + "\"")
          );
          T = typeOf val;
        in
          if (T == "string")
          then
            (
              if (substring 0 1 val) == "." # to handle enums
              then (printId val)
              else ("\"" + (stringEscape val) + "\"")
            )
          else if (T == "null")
          then T
          else if (T == "int" || T == "float" || T == "path")
          then (toString val)
          else if (T == "bool")
          then
            (
              if val
              then "true"
              else "false"
            )
          else if (T == "set")
          then ".{" + (concatStringsSep "," mapAttrs (k: v: "." + (printId k) + " = " + (nix2Zon v)) val) + "}"
          else if (T == "list")
          then ".{" + (concatStringsSep "," map nix2Zon val) + "}"
          else # "lambda"
            throw ("invalid type " + T);

      rillConfig =
        pkgs.runCommand "rillConfig" {
          CONFIG_JSON = builtins.toJSON cfg;
          src = ../../../bin/json2zon.zig;
          nativeBuildInputs = with pkgs; [zig_0_16];
        } ''
          mkdir -p $out
          cat $src > json2zon.zig
          ZIG_GLOBAL_CACHE_DIR=$PWD/zig-cache zig build-exe json2zon.zig
          echo "$CONFIG_JSON" > $out/cfg.json
          echo "$CONFIG_JSON" | ./json2zon --dot > $out/cfg.zon
          zig fmt $out/cfg.zon
        '';
    in {
      source = "${rillConfig}/cfg.zon";
      onChange = ''
        notify-send "Home-manager" "Rebuild nix"
        killall -9 rill && rill & disown
      '';
    };
  };
}
