# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod"];
      kernelModules = [];
    };

    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/22c100c7-3caa-4c03-87d7-b98a945251d8";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/0499-6E9A";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
    "/mnt/old" = {
      device = "/dev/disk/by-uuid/8def0567-4745-4356-832f-f9d0161f800c";
      fsType = "ext4";
      options = [
        "users"
        "nofail"
        "exec"
        "x-gvfs-show"
      ];
    };
    "/mnt/win" = {
      device = "/dev/disk/by-uuid/528204CE8204B90D";
      fsType = "ntfs";
      options = [
        "users"
        "nofail"
        "exec"
        "x-gvfs-show"
      ];
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/291a4626-6e59-41ab-9637-386ff5ec3d20";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp45s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
