# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod"];
      kernelModules = [];
    };

    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/8def0567-4745-4356-832f-f9d0161f800c";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/FD98-2F4E";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    "/mnt/win" = {
      device = "/dev/nvme0n1p3";
      fsType = "ntfs";
    };

    "/mnt/tb" = {
      device = "/dev/disk/by-label/tb";
      fsType = "f2fs";
      options = [
        "compress_algorithm=zstd"
        "discard"
        "noatime"
        "nofail" # Prevent system from failing if this drive doesn't mount
        "users" # Allows any user to mount and unmount
      ];
    };
  };

  # fileSystems."/swap" = {
  #   device = "";
  #   fsType = "ext4";
  # };

  swapDevices = [
    {
      device = "/dev/nvme0n1p5";
      # size = 8956; # MB
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp45s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    nvidia-container-toolkit.mount-nvidia-executables = true;

    nvidia = {
      nvidiaSettings = true;
    };
  };
}
