inputs:

let
  inherit (inputs) nixpkgs nixutils self;

  forAllPkgs = nixutils.lib.forAllPkgs nixpkgs;

  mkHosts = nixpkgs.lib.attrsets.mapAttrs self.lib.mkHost;
in

{
  lib = import ./lib {
    inherit inputs;
    inherit (nixpkgs) lib;
  };

  # darwin hosts go in darwinConfigurations
  nixosConfigurations = mkHosts {
    # keep-sorted start block=yes newline_separated=yes
    kazuha = { };
    # keep-sorted end
  };

  # drop-in modules, usable without the rest of this repo
  nixosModules = {
    # keep-sorted start
    amd = ../hardware/amd.nix;
    i3 = ../wm/i3/nixos.nix;
    niri = ../wm/niri/nixos.nix;
    river = ../wm/river/nixos.nix;
    wayland = ../wm/wayland/nixos.nix;
    x11 = ../wm/x11/nixos.nix;
    # keep-sorted end
  };

  homeModules = {
    # keep-sorted start
    i3 = ../wm/i3/home.nix;
    niri = ../wm/niri/home.nix;
    river = import ../wm/river/home.nix { inherit (nixutils.lib) toZON; };
    wayland = ../wm/wayland/home.nix;
    wm = ../wm/shared.nix;
    x11 = ../wm/x11/home.nix;
    # keep-sorted end
  };

  checks = forAllPkgs (pkgs: import ./checks.nix { inherit pkgs inputs; });

  formatter = forAllPkgs (
    pkgs:
    pkgs.treefmt.withConfig [
      nixutils.lib.treefmtModule
      {
        settings.excludes = [
          # generated by nixos-generate-config
          "hosts/*/hardware.nix"
          # not ported yet
          "old/*"
          "bin/*"
          "config/*"
          "src/*"
        ];
      }
    ]
  );

  devShells = forAllPkgs (pkgs: {
    default = pkgs.mkShellNoCC {
      packages = [
        pkgs.just
        pkgs.nh
        pkgs.nix-output-monitor
        self.formatter.${pkgs.stdenv.hostPlatform.system}
      ];
    };
  });
}
