inputs:

let
  inherit (inputs) nixpkgs nixutils self;

  forAllPkgs = nixutils.lib.forAllPkgs nixpkgs;

  mkHosts = nixpkgs.lib.attrsets.mapAttrs self.lib.mkHost;
in

{
  lib = import ./lib {
    inherit inputs;
    inherit (nixpkgs) lib;
  };

  # one line per machine, the defaults are arch = "x86_64", class = "nixos".
  # classes: nixos, wsl, iso, darwin (darwin hosts go in
  # darwinConfigurations). see README.md for adding one
  nixosConfigurations = mkHosts {
    # keep-sorted start block=yes newline_separated=yes
    kazuha = { };
    # keep-sorted end
  };

  # drop-in modules, usable without the rest of this repo
  nixosModules = {
    # keep-sorted start
    niri = ../wm/niri/nixos.nix;
    river = ../wm/river/nixos.nix;
    wayland = ../wm/wayland/nixos.nix;
    # keep-sorted end
  };

  homeModules = {
    # keep-sorted start
    niri = ../wm/niri/home.nix;
    river = import ../wm/river/home.nix { inherit (nixutils.lib) toZON; };
    wayland = ../wm/wayland/home.nix;
    wm = ../wm/shared.nix;
    # keep-sorted end
  };

  checks = forAllPkgs (pkgs: import ./checks.nix { inherit pkgs inputs; });

  formatter = forAllPkgs (
    pkgs:
    pkgs.treefmt.withConfig [
      nixutils.lib.treefmtModule
      {
        settings.excludes = [
          # generated by nixos-generate-config
          "hosts/*/hardware.nix"
          # not ported yet
          "old/*"
          "bin/*"
          "config/*"
          "src/*"
        ];
      }
    ]
  );

  devShells = forAllPkgs (pkgs: {
    default = pkgs.mkShellNoCC {
      packages = [
        pkgs.just
        pkgs.nh
        pkgs.nix-output-monitor
        self.formatter.${pkgs.stdenv.hostPlatform.system}
      ];
    };
  });
}
