[[block]]
block = "custom"
command = "curl -s 'https://wttr.in?format=%c+%t+%h' 2>/dev/null || echo '🌡️ --'"
interval = 1800
format = " $text "

# [[block]]
# block = "custom"
# json = true
# interval = 60
# format = "$icon $text"
# command = '''
# PING=$(ping -c4 1.1.1.1 | tail -n1 | cut -d'/' -f5)
#
# # Fallback if ping fails
# if [[ -z "$PING" ]]; then
#   ICON="󰪎"        # No network
#   COLOR="#ff5555"
#   TEXT="N/A"
# else
#   ICON="󰀂"        # Default icon
#   COLOR="#ffffff"
#   TEXT="${PING} ms"
#
#   # Classify ping and update icon/color
#   if [[ $(echo "$PING < 50" | bc) -eq 1 ]]; then
#     ICON="󰀓"      # Excellent (strong signal)
#     COLOR="#50fa7b"
#   elif [[ $(echo "$PING < 100" | bc) -eq 1 ]]; then
#     ICON="󰖩"      # Okay (average signal)
#     COLOR="#f1fa8c"
#   else
#     ICON="󱂠"      # Bad (high latency)
#     COLOR="#ff5555"
#   fi
# fi
#
# echo "{\"icon\":\"$ICON\",\"text\":\"$TEXT\",\"color\":\"$COLOR\"}"
# '''

[[block]]
block = "custom"
command = "lyrics-line.sh"
interval = 3
format = "$text"
hide_when_empty = true

[[block]]
block = "temperature"
format = " $icon $max "
good = 50.0
idle = 65.0
info = 75.0
warning = 85.0
interval = 10

# CPU usage
[[block]]
block = "cpu"
format = " $icon $utilization "
format_alt = " $icon $barchart "
interval = 2

# Memory usage
[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:3)/$mem_total.eng(w:3) "
format_alt = " $icon_swap $swap_used.eng(w:3)/$swap_total.eng(w:3) "
warning_mem = 80.0
critical_mem = 95.0
interval = 5

# Load average
[[block]]
block = "load"
format = " $icon $1m "
info = 0.7
warning = 1.0
critical = 2.0
interval = 5

# Disk space
[[block]]
block = "disk_space"
path = "/"
format = " $icon $used.eng(w:2)/$total.eng(w:2) ($percentage) "
info_type = "available"
warning = 20.0
alert = 10.0
interval = 60

# Network
[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

[[block]]
block = "bluetooth"
mac = "00:18:09:92:1B:BA"
disconnected_format = ""
format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "sound"
format = " $icon $output_name{ $volume|} "
[block.mappings]
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "Speakers"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "Headset"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
format = " $icon { $volume|} {$active_port |}"
[block.active_port_mappings]
"analog-input-rear-mic" = "" # Mapping to an empty string makes `$active_port` absent
"analog-input-front-mic" = "ERR!"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
info = 60
good = 60
warning = 30
critical = 15

[[block]]
block = "backlight"
format = " $icon $brightness "
device = "intel_backlight"
minimum = 5
maximum = 100
cycle = [5, 25, 50, 75, 100]


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
